In [8]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('../scraper/data/ads_storage.db')
cursor = conn.cursor()

# Fetch all data
cursor.execute("SELECT * FROM ads_raw")
columns = [description[0] for description in cursor.description]
rows = cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(rows, columns=columns)

# print(f"Total ads: {len(df)}")

conn.close()
df.head()

,hash_id,title,link,price_m2_eur,price_m2_bgn,size_m2,description,floor,akt16,energy_class,potreblenie,broker_commision,additional_notes,status,created_at,last_updated
0,f86956dd334888697e09f28acb103cf8c9dfa00f0bc5d6...,"Имот - продава Гараж, паркомясто, в София, Обо...",https://www.imoti.net/bg/obiava/prodava/sofia/...,None,None,None,None,None,None,None,None,None,None,pending,2026-02-15 16:58:14.999578,2026-02-15 16:58:14.999578
1,54f96cec5e494e296451bd6588e2153de45b96bc8846ab...,"Имот - продава Парцел, в София, Банкя (гр.)",https://www.imoti.net/bg/obiava/prodava/sofia/...,None,None,None,None,None,None,None,None,None,None,pending,2026-02-15 16:58:15.008348,2026-02-15 16:58:15.008348
2,db86942d1b1b8fc970e32022d5f548165d9813d4212ad3...,"Имот - продава Магазин, в София, Гео Милев",https://www.imoti.net/bg/obiava/prodava/sofia/...,None,None,None,None,None,None,None,None,None,None,pending,2026-02-15 16:58:15.008562,2026-02-15 16:58:15.008562
3,ca420156d8e9fbfbd273afed51b5b294de1496404facea...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,None,None,None,None,None,None,None,None,None,None,pending,2026-02-15 16:58:15.008903,2026-02-15 16:58:15.008903
4,528685330d09ed04f6d4182b1b75bff4340766ce5aac35...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,None,None,None,None,None,None,None,None,None,None,pending,2026-02-15 16:58:15.009103,2026-02-15 16:58:15.009103

In [16]:
conn = sqlite3.connect('../scraper/data/ads_storage.db')
cursor = conn.cursor()
# Fetch all data
cursor.execute("SELECT hash_id, link FROM ads_raw WHERE status = 'pending'")
columns = [description[0] for description in cursor.description]
rows = cursor.fetchall()

# Convert to DataFrame
df = pd.DataFrame(rows, columns=columns)
df.head()

,hash_id,link
0,f86956dd334888697e09f28acb103cf8c9dfa00f0bc5d6...,https://www.imoti.net/bg/obiava/prodava/sofia/...
1,54f96cec5e494e296451bd6588e2153de45b96bc8846ab...,https://www.imoti.net/bg/obiava/prodava/sofia/...
2,db86942d1b1b8fc970e32022d5f548165d9813d4212ad3...,https://www.imoti.net/bg/obiava/prodava/sofia/...
3,ca420156d8e9fbfbd273afed51b5b294de1496404facea...,https://www.imoti.net/bg/obiava/prodava/sofia/...
4,528685330d09ed04f6d4182b1b75bff4340766ce5aac35...,https://www.imoti.net/bg/obiava/prodava/sofia/...

In [24]:
conn = sqlite3.connect('../scraper/data/ads_storage.db')
cursor = conn.cursor()
# Fetch table info
cursor.execute("PRAGMA table_info('ads_raw')")
table_info = cursor.fetchall()

for col in table_info:
    print(col)

conn.close()

(0, 'hash_id', 'TEXT', 0, None, 1)
(1, 'title', 'TEXT', 0, None, 0)
(2, 'link', 'TEXT', 0, None, 0)
(3, 'price_m2_eur', 'TEXT', 0, None, 0)
(4, 'price_m2_bgn', 'TEXT', 0, None, 0)
(5, 'size_m2', 'TEXT', 0, None, 0)
(6, 'description', 'TEXT', 0, None, 0)
(7, 'floor', 'TEXT', 0, None, 0)
(8, 'akt16', 'TEXT', 0, None, 0)
(9, 'energy_class', 'TEXT', 0, None, 0)
(10, 'potreblenie', 'TEXT', 0, None, 0)
(11, 'broker_commision', 'TEXT', 0, None, 0)
(12, 'additional_notes', 'TEXT', 0, None, 0)
(13, 'status', 'TEXT', 0, "'pending'", 0)
(14, 'created_at', 'DATETIME', 0, None, 0)
(15, 'last_updated', 'DATETIME', 0, None, 0)

In [5]:
import sqlite3

conn = sqlite3.connect('../scraper/data/ads_storage.db')
cursor = conn.cursor()
# Fetch all data
cursor.execute("SELECT * FROM ads_raw WHERE status = 'done'")
pending = cursor.fetchall()
# Convert to list of dicts
pending_list = [{"hash_id": row[0], "link": row[1]} for row in pending]

# Or if you want column names from cursor.description
columns = [desc[0] for desc in cursor.description]
pending_list = [dict(zip(columns, row)) for row in pending]
conn.close()
pending_list

[{'hash_id': 'f86956dd334888697e09f28acb103cf8c9dfa00f0bc5d6bec99a5fae51bc5751',
  'title': 'Имот - продава Гараж, паркомясто, в София, Оборище',
  'link': 'https://www.imoti.net/bg/obiava/prodava/sofia/oborishte/garaj/6196041/?sid=icNBCK&page=1',
  'price_m2_eur': '3 333',
  'price_m2_bgn': '6 519.43',
  'size_m2': '12',
  'description': 'Строително-инвестиционна компания Идея Хоум, предлага паркомясто №35.9, в сграда Опия, в сутерен. Района е с добра инфраструктура, с бърз достъп и добра комуникация към бул. Сливница. Сградата е разположена в локалната улица Ангиста, точно след Агенция "Митници".Теренът, върху който е построена сградата, се намира в непосредствена близост до центъра на столицата. Пешеходен достъп до възлови булеварди, метростанция Лъвов мост и спирки на градски транспорт. Сграда е с разрешение за ползване 2024 г.. БЕЗ комисионна от купувача! За повече информация: 0888 387000',
  'floor': '',
  'akt16': 'Да',
  'energy_class': None,
  'potreblenie': None,
  'broker_commision': 'Не',
  'additional_notes': 'Посочената цена не включва местни данъци и такси.',
  'status': 'done',
  'created_at': '2026-02-15 16:58:14.999578',
  'last_updated': '2026-02-16 16:43:51.616580'}]

In [13]:
df.to_dict()

{'hash_id': {0: 'f86956dd334888697e09f28acb103cf8c9dfa00f0bc5d6bec99a5fae51bc5751',
  1: '54f96cec5e494e296451bd6588e2153de45b96bc8846ab3221f791d5411aa812',
  2: 'db86942d1b1b8fc970e32022d5f548165d9813d4212ad31053acee02de36b772',
  3: 'ca420156d8e9fbfbd273afed51b5b294de1496404faceae7b353c0c952d719b0',
  4: '528685330d09ed04f6d4182b1b75bff4340766ce5aac35e9dee7501aec374deb',
  5: 'b6c286ce2e6de97589316b15c742cce2b09e5b655ba169ba19883fc3ee9a0261',
  6: '9a0fa18467acc9749700e245657c32afdf868653c06d874615bb555591dd91b5',
  7: 'd4bc76fbc196bf3af9ccb2d2caae76b3b17f5980083ba31bed3cb7133d0e7ba0',
  8: '36e98b5a412b623b6021988f0acb72f50f571bf84bec3c872a4e2ea1aa318282',
  9: '7d02afcb09b0d7cebacec987663f05515e0386457543b8546b6fa85c5ebf1823',
  10: '27fb3fc23d876d654631bc42a6a1376055c7948cf75e95fd2534b7a7a12abbee',
  11: '32693a15a3d41f6871dc5feffed1db7a0885aee6fa56fb92f3b1e819c65d76a1',
  12: '61aa28d52d4c0bcc691567726316f400c98147388bd4bc0da192df6cd25a811a',
  13: '89c1995e424ee9549901541ee6fdd41723d65f3a0d1d0a06548d413dc62d8571',
  14: '64d07d8d6c1dec8dc577dc29b99b395b31c2030f9c5a9cf5928b5d0ddb176936',
  15: 'b17552c11e6af659c1b746bd28f4beb1f2f282d50ba428e67176e505db84eb7a',
  16: '6ec0c60cdb991d3a5b23ad9079912011de2a8f74b76b83ebd6c21458550fc699',
  17: '41ca4a77b4a83fd7f48c20c2b167ce28f9a7f78c9a4d184fd9aacab56c6fd329',
  18: 'c356733988bd254f6611d6880159eea2060ce4c731174a618f4d8c38eaa88fdb',
  19: '1d1faeb585a8b231928ac469e7c038c504f7d8adedd292591b2da476cce05f2a',
  20: '749b5960d58dae8f888b729cbe72fc35a04a80debdab957e6514e665503198a3',
  21: '2c2b318da933a140bf5a7830ac7cc9b2500f983bf0549bc226440db39e1c0c48',
  22: '835908ad36d1b9b442e5dc52dc49a4ba53d5e22b1cb98556a0a1841ae707441c',
  23: 'a925de7efa3c02d06a96ead9ac885aa69bfc3dba974f4cbb14df96497489b3ee',
  24: '0fa5856cf7f3b5e0dbc36d4b86d154a733e1b532566db822d2c2c11228ff8477',
  25: '0d430858f834ecb2ea304f0251ba617c4a9cfea3a9e0bf0dbcc1a7eb3c5bcd6c',
  26: '253f9dc2e3567965ec80bf21848f4916086124163371ffdd30717ea79a992dd6',
  27: '0b25cf1492307fa262c18c0a40988ed31bd5c85a4da80f823475bf6f7788cb53',
  28: 'ffbf47d4fe4629233249192850dab264299b118ed440b671807622e9042b88f5',
  29: 'ff160fa3b6f34e5da4a50e27f228ab05aa54ee30453b1904a1e5c2880a3298f9',
  30: '44386c4f4709d908d92c13583d36e3d400580c6e2f63a46dd97a5b2aad6e3eb8',
  31: '169f89135d8242464d82fa77a00aad672fe8430125f4930149ed83dfb5d78f37',
  32: '1b043d9800d223df92a25090e02eeee9559d866036f23888b19ba738c376b3c9',
  33: 'c52e8d9b620c878141d8b8803b386c17969d60627387b761dc9270547fcd4f9f',
  34: '4d162c833f69df881a1854a12fa31bce2f7500de7b8b40b3ab9b42d0a4381d93',
  35: '8c3ce9d4d3fc4de0c7b58f953a05f882c75e336441f439c819ff6474cd4900e1',
  36: 'f427dfa7183715c976ca5801c47f60c82bea474435748bf850ca2b5a3f88e1bb',
  37: '41ef2101fe1ba21750acf80ff4ca8335fa90752fcc2e59a89a26c4f75a160aa8',
  38: '754d7e43de3e24d76a9b58d19ce2edc511907e9054e6be85a8e912b6c7d220c2',
  39: '63019e486ccfbd6ec0406a3487f913b3057c6ebea33e9e2a785ca455e274d51f',
  40: '5f8a125ffaf0f7a0d094666d5e8f3a3bbc0b637c1d96e4bc605b5c36adcfc266',
  41: 'f202f8c39b1ac203bf33533a57ddf62de28f10cb23c101b6ad7606017336693f',
  42: '532b9a97eb20dd4103b1af6229f8418b7198ae142658700c07b6c45272507980',
  43: '8246388aea3aa231194a4f1743574316eede09d57b2558d09037571f366cce6c',
  44: '83e05116a7d0411efa1cae9622bbb29011b303c1ab56636c454dc5d2df808799',
  45: '50f4ebdd131284f31855f242ac70aad392118f274a8747a34a583eb3ef9d7173',
  46: '0e06af59662fe9c379b7c5288fdc52051c5f4aa6869af56df0121dce8d185620',
  47: '8fc997659555021c9963a30269b5cdca7edfeee41a794ee549c4f18e7bb36add',
  48: '55a6bbba198976be508eb55616912eca3fe22b913c950f36a159b3030c2d488e',
  49: '758c2a1aaa6b00280ba091fc2466a06b3ec5c7adadf2295ae54d7c2c3d1e1445',
  50: '90e1df43c39cc15306efe09666b74b544fe12a9ece19f409f5199fb01011767b',
  51: '79478a3c5b7e7fa64c5ae2d1f1a4d0b53f556ec22875e56c33e6401c0a040491',
  52: 'c9d231495a0730b5ead398a03b847aa43e0280596deddadf61408bc74e019df9',
  53: '12b15ecee8ac44ef54fe8a89f230ca57e884488691280e3ed6aa511fa4017697',
  54: '400dc33bfc4720afa1eb0249a778d01e815b3546240b2951960216fca5847018',
  55: 'aeb810b632a8bd6ebecdb8bb62041d5a4736f3dca6518ffbe2623e78b9313141',
  56: '9a7ad68d5c031e0a8045a352fe289e6600bcf3ce7a9725b81daacea3f28059b7',
  57: 'ac04d3c13c5db40c15a2777df92875ecd7131a843bc79175fadf2f8551e250a3',
  58: 'eba3f25db966410951bf01c714f01e0a7b9c70fa38cfae9ea261a0f9ec339410',
  59: '2e80cee57839a8486e439b543d1a80ef1e4a983114dc033c0ada03b1b484645d',
  60: '843354d0a2de9a87409b8ae3c23cac636969b1d88a46829258a74d13aa544d8e',
  61: '0716fd45b65a8f6bb0a15b8cee4fb87a45a843ee6532590ceea57b0c357f6ab4',
  62: '177303dd2dacdcae69e8f1549806978426e6221fcc5b1b3e6b0bc00deb5780cb',
  63: '229095fb28ba13bdbdb556a7faa34c16cf91f038cf2c069f8c3d37d7b3bd9bf5',
  64: '5d35b22aab4d6a9a1ddda1aaa48ecd583377fdb065f49f28a4bd5293af1a49e6',
  65: '77ad8b47f99e50ffe752f34b681f19559a0d7dd33b87bc5f25419a1e321bb324',
  66: '144c594889d20d5e7be19c8f7c4454611d30257aae6d76cf453234209fbf519b',
  67: '43084295b7cd32cf6691008367f0ff87635e0ddb81bea19a3bbf1ef4be11b287',
  68: 'a2f16a65dbceba5bf76c27ac6aaaa99ef18d1daa7ff9d5663b9d8bc0e43b1f2a',
  69: '5fffca988685ac4f8e4aff0c6491aaa4432ebbca91e088181ba67c169dca828f',
  70: '87d0b116bb5cd3af6175419046b053b89cdbc03c5c7ef7110c623c40a7c0243b',
  71: '3a23d82b71038aef761614f4cd22e3e040f35175c6fe23d8157fb897d7f3e6d7',
  72: '334ac90d88bb657990745020360eefb15127876048a4031f7830c4c1546cf67d',
  73: '1769d9799bbd140ccfa506aee060ba5f29ec5c3d2eeabe817320e33972561991',
  74: 'b69a8f75894c376c4374da212a20e8d89aced517af7537c6001a206e849f7903',
  75: 'ae4e26a9d996035fa6b3a07196fa4d41ef739fe15fdd964ca14494d8f79331f9',
  76: 'f081ddb266628d3e97c8172c86d2077729ad4c2a7946b1cca5094a4a5a2b1f99',
  77: '1e9df0cd7fd794144a8d7ee4500fb74a01a913cf619e7ab96d22c35792536018',
  78: '3e107b7e295dd9122ef61ef8da23184428eaf11f980063dca7a2939c989322de',
  79: 'd03a049c296a031eb10aa0bd356910827f48079be356fe4390985201d459b4b7',
  80: 'cb7a0d8e5838b79e048566e39e9ab1eb5deb4c1e7016c5cbb825fb4e2406b6c9',
  81: '7fedfe21ca130a9d0e4c94939728b4dbe648cd317c4e9102ffb1e0cc25de99d2',
  82: '9f04011297066fca2efda1d2ee5b394312bf827924ac40bba6fb6e0fd29a72f0',
  83: '81dae10dee7a016ebadb6b06e81e5dcbcc3f5accfb070acc76eaa8da409d5982',
  84: 'e02e86d4dc3673115af2e2fa57bd64bf5133cca9f11426bd6ef25ce80ba7b93c',
  85: '2e2585543a94e510163471c4888e6fe44c810121b5b4d81e90f8461fb0074f04',
  86: 'fda417c6e99d732b9c0b7823731ae2a71d63bddfa38af4fee046464d214192a3',
  87: 'f8e70db222ee2dd2a9ea06f72e447df0c7e81187d9b205d43ccc912504144892',
  88: '4445559630e9411d386ec3aec4e4c6bcd71ab29262ebcaa2d52e321654234cca',
  89: 'efa3e42270b29b85de138bfe088cb3997c801429b72e4e873d0ae7b0bde494e8',
  90: '1b0acfbe1fdf0fd76b6997b4daa85a0d2a73bd909358a39cb5f564d18a082d2b',
  91: '6875f619d58f0e76ca9aa98664e226c8679e0a5018bd76084aac0462008b6573',
  92: '29bb824d1c55f4b93c90600afd6df6014cc8fe35f1c245f69d114bfa9e4be821',
  93: 'a79701200a8e54874acb7e70ce35da59310b0a183befc9a1c684f9e53205e39a',
  94: 'e327081612c6c20cfe75dcc0dd0d660489c817a448cb868b3371113f5aac3d67',
  95: 'd18d0ad025b14a3f1a686a72227e9a09e907dadca93bc22f3430f511430dbcbe',
  96: '78df5de8534829020fb50d029ff5c54553eef5464a0342c0b346e67578aa536e',
  97: '9899c9de7634db043708050ef5303695ac300f7c6556ce8397a2776c7ac8510c',
  98: 'caa7aeaacb99e0a0c03e76fc20e83852a30d897dabc94fffa15139ccddc3c7b0',
  99: 'ea6f86f89e89e667516970e30499b8aacefa29d05080e9ea6e5cd67bc6f5b976',
  100: '2c0f391bfebfd2d4a4ca9a4d09fee0b36de877b6d87f552b058a5c16a9f9e8fa',
  101: '8462c88799f98de8294a941346a8c5ce4e8744d05220ddf1b6ff7399ab4e981d',
  102: '58a0f3f5c69f03271c8887378ed90de7d27d73f65393a5b8caaf7a10789a67a9',
  103: '2feb9996bf07b00b9b6d46d9ffe2e535d1a86dbb3b2fb0bc297efd3fc4713cdd',
  104: '91ab09f2154c994a4feffbae445c7cc2d95e27f0bb4dad2f6ee281e8f669066e',
  105: 'bdbddff2cf38f99d183133d5bec0f5330cf1202d00e41a143b914a8976da3964',
  106: 'e3cfa7fb4b29aea45dfbc6bcd6883791ac52508e43581b792979451f490d2694',
  107: '077fa313ded2e3c9425239ef6cc9e8d7bf577e3c01d5cb7027d78b07e1b32c9b',
  108: 'fd01fd2267d8b53c498edbac2b4318b334d30b2d279f01dd7bd36b16fc3b0171',
  109: 'c5492cdffa651448414f7c2f619068740c78ddfd21ebfe97aef343794f114463',
  110: '7aaedf47a8e05f83c63c76efaeacec1c3d08ecf933dda03590e4256439641363',
  111: 'd30adc78aa1a0e89d040e7d803e73460e51a03525950d533d2fb3eaf0c6573b3',
  112: '79be34baefc03f991229927f91b3c1e066eca95dfa8f1adedd9ff9d00e31813d',
  113: 'd3cd22d9616e57ba282cc8af1b9d9e269815c4498453163cb08a1d7a84d4a3b1',
  114: '4e3da434923d49586f0e0a56a7cfa0e8fcea831a90ed9bb1ba3d4b2eb6b45782',
  115: 'dc9269f5b7f41be8961799fc805c818ee56bfed019a346766bf429b9dc468f7c',
  116: '98603602c3d98b7f40a06882f2df7895e2f73cec42b2a68903252c5975ff58e6',
  117: 'a0b39991e6b7d239c48728ce9f389b36a230f4401425a37c8571e1e2342d9bdd',
  118: 'd40468c038c445bdda5075722c545c4d4ab17a86d1dec9e36a6921510f359a2c',
  119: '1ef28ed6185bfd592fc2a042a889731211b4ee530433f5b4098864b9a21b18e9',
  120: '1186f3c4dde998a637ae90ce424b525997b565a05abb4a79649c676360ce3689',
  121: 'f48173b9941fbd32dcb68887290c61dc094c03acd4123357db02389e3283f92b',
  122: '1041a7002e861500ae697d6bd4d031658c0702d168503f7b307af02c62ac47e7',
  123: '50573ba11ac4b733ee8bd2b0a9db42d606fc8725903b741f50403cf3ca34e1a4',
  124: 'e8d5c5e41b8b9b13312c0fd515d42e697803752d62e9783c7411bea4d21f2c5c',
  125: '7dd3626f62a15fb48b37e9e5114c63c1f9eb93cf8bc2c592c59f17bbd70545b8',
  126: 'ad7f0100644401dd88e65606dec393be20879251a482890c160cba01717d38e3',
  127: '3ea159cb0dc0fb70c774935cbea5a8c7c53bd4c842e794c1228e57bfd86b50d0',
  128: 'f6745f95d4a0463f0feec110f6e32c95e928df3a3c31492f3bf7fa9237872a41',
  129: '504ff6f137a1d7b378a7bb2f5d779410e90d0a7071da1f336152d6a95c1ffe4b',
  130: '6046312b503e4f1c90c43896b82f62ad4727432edf4947e1d10fa59896670634',
  131: '51c9c650e0c6cae6cc23dc4746cc8a5a6264647bfc4cfeabf93c73c4da63d761',
  132: '977debbb39bff1815e032a18e329be8ee30cceedb5c99298201c33d850ffb462',
  133: 'dd793431e45c8dfc476fe8098d8f0d51db4520346e1ac3f3edfeb26194529b81',
  134: '1e6c4ec9201d701e36299e9aca1c2fb389231e77d75a4b2fdc3b50b30e0d2ef9',
  135: 'be0c23a1a967c66a7c109619a770580e8bdb253d031f286b2a976c4cfa8628ca',
  136: 'b6816fe92c3c746f5264006541f66980e1e5dbd45d894f30a199ba04392347c4',
  137: '12c12487cbb898edd7ff280243b00dc0b65aead7a3db5d396ac578e10c4af4a8',
  138: '85781862a170e45a930b3abd232d7b149d6fa8ab2ec8e7fce10715e4a19edc5f',
  139: '60eec7357e071b142da2e84ffbc31dc196414daf1079dfbe1a9f95ead34df0a4',
  140: '3044465ba4782486bfd403d5f9538856ac66baf00875ab15655c28ce8f87b243',
  141: 'e2d4f934729308f161b8479cf336b9e9de1ffafd9e92fedf5d7e1896284a8a1f',
  142: '5fed4a9b82376ba310aebebcddfb847701e1ce5f358c95efb9cf87bc3fdc966a',
  143: 'ca14858b030ea16de05b5da07e9b86fa1552845323a9924f0f1db8f2b3b7b108',
  144: 'f3a98f0121de1920a8e0c4eec489bf7aaced662edd2b3f67369efb6156e13115',
  145: '7b68698f8ee749590722be7559edbbea578f8f8cbedeb557cc554a45606654fb',
  146: '5f96a892e8afc5c2468b48053dcee247cc4504fa6d54129156e534f2a2a0465e',
  147: '07d08b994e12da2f625915e9683689677e78fa272f3f7ce443296ef51fa44ae0',
  148: 'bf530a4f834cb7ed395740c0f5917b352a8a2b9dcb37cf0f80db6d03698128b2',
  149: 'a062905440261d222fe4cb5941b446d7f165ed74599d9bcd418881d87fc6e041',
  150: '8e7525d5782bb34adf8d04f4e48fe94a98270c477befb5c9d984ffe968b88836',
  151: '477c29bb2bc467641947e224c18757b11d0b1babac6098486734d40fb15260c7',
  152: 'c520776ccf334a658de48743520c9faba02111217936d78fa86b990b04503ef4',
  153: '8f1d87b0f6a0d8ba11f237a4c74ed96a03bc8c760d7817babb82d66de057eae6',
  154: 'c24d92a48009979c5119c34ebb93120afe5d6feac3d978727a6dd4bc8a86f289',
  155: 'f223fc565c7ef63b3d617d0703eb0d79fddc13e825b5c71b998e4e387dc8f5b5',
  156: '56cd6e881ca329fae45750f914416a285a504c062e4af962eafdb0d6731ad3a2',
  157: '4fa313a26871b058e7dfc7cf879609d29ba3199af2e574886c3ee40c189fed32',
  158: '15b18afd38df63a7d061769374bb40263b6cd182f153d0cc7e2f5a7fedb95c9f',
  159: '531b61e84064373a819f82f2a0323fc52a01ea017a0213a91dc9cb46d8aaf7c7',
  160: 'f72a2c294f49f7c13532750cab1b3c9f2f8677d942fa9eb0a6b3b8a53149a7ec',
  161: 'dac2107ecfb244231bed2fd413ed826e18a521f2aa6d523bc0a0ed5becf84559',
  162: 'e6ac39ac8959130b1632826a8eb8cf3a0ff8fdc8f90f142655dd1da2d888b101',
  163: '61c94b57c2436f08375cbdd742041f837cd03537785bdc9e159aa34d03c95bb3',
  164: '2cf0f35b2949c7b9fa4596e6bef030a5570ec811dc01988d3f9a79c92730fee3',
  165: 'd5cb325ebef5b268df503e19946506f08e8062a8b2d4cc6ff9042af32fc704ac',
  166: '0b5057a581a1efc751a851287ff6fa30045cd8c60ebc3619508685aee27696e6',
  167: '7de8f920f70866d9ac59ad4033428b66e8ae7d10b530c4436e95166cab620483',
  168: '5ae7d3e3c56655c58baa55c2502e0eb44ec386b8d8f98b5253e370a6c1a16f2f',
  169: '46bc795ef7f38701dfd62c0e136e636d74f973350f7bd1c2acd51b35d9b6a5ab',
  170: '9ad8f7234f8323f3e04b5d2687d205c530b6034b0aaa3265d4bceab629c0e047',
  171: 'f86677511c308d1d0ae318402523bf2fc165918c9afb417a6ad36555f7f6476e',
  172: '0ae8da5d48e4d95280559375bb34835a398530f5cafb9779698eaa04e0f0b376',
  173: '24218f7ee1c91286232ae103ce46759c3b72d7a466248647fec0e95ecd7e973c',
  174: '616a35c1c013a72063bcd2bc640f03e6dbc38718c31a5dbe963bc5af8aac9150',
  175: '323d6834d4d55dc24ecc29416e2a181cd18d63ff8ec591371410b8ea24fa0b20',
  176: 'b08d1d96847779dbfc0439966a1ddd92c651a200f95077aa3ba2a8f72a546c81',
  177: '61b350032fefd16b9653c2e875c5c11d6fd84db99312e47914266318759e1610',
  178: '5a6f04b4e2eafdce9f8b893cb0f3692943746be8688f4a34d5984e729300e720',
  179: '527a44f28e5f8181210fe26fea72c9550e21758e720a0e2d812cbbad9b7d4016',
  180: '52caa5904034aa94b3ce3a9eafa4559a637f9c3d2f9a3162fcc08c705a311f08',
  181: '1a0e41fe3ac9134d087f718f2abb8e8aa0efe9bf67b646ad0b481ef8dd64d720',
  182: '9053115b446eaaa19456aef00628df707c0b5da802cbca9cece74d5937bd184e',
  183: 'd88168ad9be374d39f04d07a412ccfcf757875e923f9079890250c381f30f256',
  184: '798a891c3261482e2e9a9f34f5a083564609a51710fd845b59c49823386f19bc',
  185: '139004643819fd274f0cc96c27e652d8bd4c4ed3d7c38f430202a9ead328b984',
  186: '4b54a0a7c70c96f9a199eb4239318cce139dec7f9aff4255190005158f2e763c',
  187: '7dfefc8f1ccdfd2b5a26c2fff48d835bdbd6d72b9140c69d763eaacf7002fca3',
  188: 'c2d8fa5e5f79f394bb4e0382801a955110554693eb818752bd8a2a8a25900c88',
  189: '7bc5213fe86d3663becd4e79337fec073fe0eac491eb3c9a0fcfce4e7dae9b85',
  190: '5f167ae8caf5331be44ab98428a767d0fd1a5f7ca7b8188a78003c7af7a7b00b',
  191: 'ceff7c0a7d1fd21c20621045f92b2fcfc247c55e6d579ab6ba66e1e9f81bc071',
  192: 'a024e8501efcca34ea794b536312a731633c19c0cdddc683548254d164919da7',
  193: '9509313bf0c1f748f3cd3d827c7e400ecdcc08555f46e085ebbbd20ddf7f5366',
  194: '8c712739a53da00ab80c347fd609ec306529708638edfe53eed9bc3aa9063f6f',
  195: 'cfc65e80753f142627e2ad21c6d47eb80e179e592b54009ce82e5b228510a2d0',
  196: 'e46ab763e707e68012fdb0c29251a2b66cf4c848eb6db056120012700b252cd8',
  197: '110ff9279d2db74e19e73abf9c83c3c1c249165d883618ef7065625a58db54b8',
  198: '42fa7760f410d293d13b4e1db713f65183055a9fd5b0c28f991ad796b10a1431',
  199: '84170d52b47edfdadf4e74ed2b081497826d35a619056ce1c4589d2cd6747619',
  200: 'd48e5ab52a7da4d9d262fd528ceab2f781f16b464420e9f2e33a38e8ecd9d4bb',
  201: '9dfb9bcd8ff3ede427058c2ae0ad7a42e3bebe5946046323e736fc87602da62d',
  202: 'f006bc070cf0c14122aa94590742e910765b22b5b6e4ebdd77e211505604770b',
  203: '05ed0f5a561052ed459b7608f84752b772ff0b21d082c36543e2aadacb1bd23d',
  204: '1cfccd0b3b298d6b882599e5d5a2f1efc25ec85d65575bc6e7a49fa4f281efc4',
  205: 'e9e5930f183a20c57331868f30b54261f5f3bb980efef4cba31997f9818e0634',
  206: '927f56f296ba7369fb75cba5469c600212b75ea7ca6aa58602f67ba48468c9c1',
  207: 'ea29d3812af5d51f34c198f23c95e9dac5a4a19cfde8e4be78e9a15612c8fc39',
  208: 'de673e9da811033bc25cf60f6b2fff83ef507b995e3aa5f6f8bda99f1b147e10',
  209: 'ed12a01ef4af60449f0cafbcbb7e2708e66c25d597e2ab0e857e87b6d58e7ea1',
  210: '3971b7372886297bf6ba9867294dc51ecaee4f802bea8b52b8a9c2a05661e01f',
  211: '5dde03d8fe0939b0375c21f8c753948c0dac33917da7fe8e9887ac1d6a41e421',
  212: 'd07b1aebe560fa8953e9256f9abb879a8cf0d6883bbd1f6dd5161d6de1e540e4',
  213: '8f7dbb2a5b8e2146704690242ff2c35ddeced6a3f3e51baab041056de05192c0',
  214: '42c7181c72ad08eb22e4159bcd543211604cf1047e1383af875c5942b232bbf5',
  215: 'bf38e19c714f02778a5f656899062cb01118bbb851151135096385e57c96b18c',
  216: '53dbe01fc024093b521388e37bb7cdfec7e55d7e1d0b9e503f8909e40334d855',
  217: 'ee05082a309f15fe3e915199f5dc1672b7ddb1f67dae765f08c98ba0af46013b',
  218: '1b5393f26dbae6db6b2b8073e389925b675d3ff1fd7eacf9268de745f29937b5',
  219: 'a39f6ffc78b956934e193515f65bf6800925750565c87079329cf4759e7de69c',
  220: '0441a2c485b7c5b032b024abab0fb7bc1f65395471ef7fbcea4e2c1f6d1eb701',
  221: 'f7f939a33dbe81436a0582e5d5784f2e7392067d9054f1325b2b581409a42afe',
  222: 'ad59ebcd77911b62dc559d1dccda729cba27919cbb81b136e45e29cecdaa0c44',
  223: '8f4e99cbdaa52b06d0c6b4364e69b96a0e27c52216eb644b4a8eefd6a9a967b4',
  224: 'a70d9850f2fd8f9fc8cf35841411c9c3824a08849ca2d23182c7add0ee46c849',
  225: 'fe3affc1dfa0566719644b5068fa205a7ed763011aba0e1b1ec999c7df144c25',
  226: '072aaabe6adaa899eaa46935e283f3f4f5ccbf065f2b2b34d4c542446c3129c0',
  227: 'd78a5aa772cde6201c1c1efca61244ff5df13b91879ba4a41e563855d7498161',
  228: '85736e130affea13cb7e748439577cdccadec1d1e6b9138599968fdf9a8305a2',
  229: '7028f91e382beac1cb6fd0b9bba4ed773d641d428cf097dac707862ad6a62e34',
  230: 'ae1fc2003fccccd0ef71a553c732e62e7aa7024a12fc60ed7f2f3991c9eae0f9',
  231: 'd99aeb02b9efb64555bdbbcc2e638ba9186ac5bbb3772718c41967fadb91b323',
  232: '20d79e849a4845809332babe11d4597b4d99b326cb9264279bdfdfd5df627276',
  233: 'cebe20b2ce45ecc95cec50de4b94b3c29f548bee2bb518c3ff2dd9e1f43bd788',
  234: 'dba51574e6338f742aba77329ed8f35b4d699a53c0f3e0cbc95e2588dd9ad1f2',
  235: '7885737146c4c6e9879ecd2c54c16a4553dffd5a1d7f488a42fbc56b68358d82',
  236: '25f88cf38d38557cb43be4288a234c44f6e308a6326993130ec3e466c2a2fe2d',
  237: '0ca5fbfbd77dbfba0f0cc99676e2f5796a8068c0fa47226e29ddd6858c72d460',
  238: 'f27340181e31ae4a6a1b2026df5096422022962ccb62c11b4f80e66578104a2a',
  239: '5760348558e0947604fb3a702b6c65460257d6798773a8dcf642e138354663e4',
  240: '1abe030eb993dc719327b00e9d7d3de80577386ae11beb76cf3e05d9cce9e9c9',
  241: '2c7f1e4de5ead01394a5be6a0a68822e169695ef78671e5b3fd8a8f1dfe1ecf3',
  242: '6be4705e79835ea9b8c30ee1325c403cd00576bf45d4e2f50adc5c000d6559b3',
  243: '13186644593d63c7e8822e1f1db0067e8194f1ffa4d9e5343d9a70d11d56244c',
  244: '5e0c3a713019988beef531403b4a185046e94c4e8ec7f1929bdd59a572cc3439',
  245: 'fe23ca7a9a4337a69796420f2d59cc2867da55b249bbc0b828233e5000449345',
  246: '2a92d143a7b9b9146b0797b8d8fe02178e30e3b510f27f340f692871326963b6',
  247: '805817af3b593cf7798cff691f1078823d73fa4e790e11a40fa8b2b357b4b10b',
  248: '84644a82dd0d856334fb1873f45a7cf24fe30ff820a574b044a2d687c6156550',
  249: 'ce6eb27a7edd3999e09038d4aaae34c532cf1e89ff10e03625330864e8faa5ec',
  250: '4ca38cf40221d576bd870781eb938a8e39cc7bd8be91dbfe2cc569896330779c',
  251: 'db35c7bae7cbbfdd07cc80f163c80aab7abd9f8814909f2494a159bc4d6193b7',
  252: '8b7f606355e9550c8c89074ecf731561054e5e001ebb547d6511b328fcc9ceb3',
  253: '45b0dfdede9b0ba68e039761d695280df329fa94f0b2c59721c72087ae2f4752',
  254: '01a6f8e50596f8886f15e9bf30bdd4fbf8280b19471f4bf442f88872163ddec3',
  255: 'f574438632b80f8ec82a40da55c7ddc2b5a58af5a561a4c2ea3a73ee48ec76c2',
  256: '09373c232d758a3001d6db6aef164d840b938fa5b4c38dbbae9d19ca734645bb',
  257: '41e6f19f9d547d08ca5046eee439758343c32b641951032ee06186c9e9da9983',
  258: '2f956f10502852687c42cb7a0bd43ada379e4a101641210d8301b67ad3149482',
  259: 'fcb4d6f626d2a2eebf8309f07b26412d24c6da691f565449aabef44953376db0',
  260: 'f1ae5d83abb7a23cd027c057ec2547fbd289846d7fd424aa787239f01550ec74',
  261: '0c22f0bfb270d293a556cd7bf254374a969ae685ab495adf9dd5593e447092ee',
  262: 'fd71f038cd4b6268e1ae80e99143394efcc880539f6b190356bbe871247c009e',
  263: '2f10f7cf9687e286f1b7d0ad1575236fe80efcab50ddf92b66df35b9b7db3f0f',
  264: '5dfca2c9a4f14e6d25b0727e43a664b908b739e5a609be8dba58c07ff7cb3c0f',
  265: '0fe544a33446b95bfd239ad18859f6eac64cbaddd21b7b8c898f47919d9b63f4',
  266: '95eda35f39753f028b1bd2d2743c3d6e5c698612f9dff8b02a1f06d4403560d3',

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11006 entries, 0 to 11005
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   hash_id           11006 non-null  str
 1   title             11006 non-null  str
 2   link              11006 non-null  str
 3   price_m2_eur      0 non-null      object
 4   price_m2_bgn      0 non-null      object
 5   size_m2           0 non-null      object
 6   description       0 non-null      object
 7   floor             0 non-null      object
 8   akt16             0 non-null      object
 9   energy_class      0 non-null      object
 10  potreblenie       0 non-null      object
 11  broker_commision  0 non-null      object
 12  additional_notes  0 non-null      object
 13  status            11006 non-null  str
 14  created_at        11006 non-null  str
 15  last_updated      11006 non-null  str
dtypes: object(10), str(6)
memory usage: 1.3+ MB